[can]
log = false
interface = "vcan0"

[system]
interval = 1000
memory = true
swap = true
cpu_temp = false
cpu_usage = true
uptime = true
network = false
network_if = "enp4s0"

[ws-server]
enabled = true
address = "0.0.0.0:8080"

[ws-client]
enabled = true
retry_timeout = 1000
address = "ws://192.168.64.1:8000"

[pmu]
enabled = true

[gps]
enabled = true
port = "/dev/pts/7"

[lte]
port = "/dev/pts/4"