[can]
log = false
interface = "vcan0"

[system]
interval = 1000
memory = true
swap = true
cpu_temp = false
cpu_usage = true
uptime = true

[ws-server]
enabled = true
address = "0.0.0.0:8080"

[ws-client]
enabled = true
address = "ws://192.168.1.10:8000"

[pmu]
enabled = true

[gps]
enabled = true
port = "/dev/ttyUSB1"

[lte]
port = "/dev/ttyS0"