[logging]
can = true
metrics = true

[can]
enabled = true
interface = "vcan0"

# Transport protocols
[ws-server]
enabled = true
address = "0.0.0.0:8080"

[ws-client]
enabled = true
retry_timeout = 1000
address = "ws://192.168.64.1:8000"

# Metric components
[system]
enabled = true
interval = 1001
memory = true
swap = true
cpu_temp = false
cpu_usage = true
uptime = true
network = false
network_if = "enp4s0"

[bms]
enabled = true
request_interval = 1000
search_interval = 10000

[pmu]
enabled = true

[gps]
enabled = true
port = "/dev/pts/7"

[lte]
enabled = true
port = "/dev/pts/4"