[logging]
can = false
metrics = false

[can]
enabled = true
interface = "can0"

[vesc]
enabled = true
id = 22
# Transport protocols
[ws-server]
enabled = true
address = "0.0.0.0:8080"

[ws-client]
enabled = true
retry_timeout = 1000
address = "ws://wannsea.eu:8000"

# Metric components
[system]
enabled = true
interval = 1000
memory = true
swap = true
cpu_temp = true
cpu_usage = true
cpu_freq = true
uptime = true
network = true
network_if = "wlan0"
processes = ["boat-core-v2", "firefox", "grafana"] # Dont know about the performance implications, maybe disable it when needed
#processes = []

[bms]
enabled = true
request_interval = 1000
search_interval = 10000

[pmu]
enabled = true

[gps]
enabled = true
port = "/dev/ttyUSB1"

[lte]
enabled = true
port = "/dev/ttyUSB2"

[imu]
enabled = false
accel_report_interval = 100
rotation_report_interval = 100
gyro_report_interval = 100
metric_update_interval = 100


[sensor_fusion]
enabled = true
