version: '3.8'
services:
  boat-core-v2:
    image: ghcr.io/wannsea/boat-core-v2:latest
    container_name: boat-core-v2
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - '$PWD/config.toml:/usr/src/boat-core-v2/config.toml'
      - '/dev:/dev'