version: '3.8'
services:
  boat-core-v2:
    image: boat-core-v2
    build: .

    container_name: boat-core-v2
    restart: always
    network_mode: host
    volumes:
      - '$PWD/config.toml:/usr/src/boat-core-v2/config.toml'
    #To Do Serial Ports etc